### ISSUE TITLE
Downloadgröße wird falsch berechnet.

### ISSUE THREAD

**Issue by Lesco404** [SALS-App/SALS#18]
Downloadgröße wird falsch berechnet.

![image](https://github.com/SALS-App/SALS/assets/81494293/94a0b8cc-6e19-4999-aded-7299369867d3)

**Comment by TAINCER** [comment]
Hey @fvsLesco,

das sollte in v2.2.0 gefixt sein. Wenn nicht, mach das Issue gerne wieder auf, wenn möglich mit Reproduktionsschritten.
